#---------------------------
# Hexo Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# Docs：https://hexo.fluid-dev.com/docs/guide/
#---------------------------


#---------------------------
# 全局
# Site
#---------------------------
favicon: https://img.cyfan.top/pic/img/favicon.png # 网站标签页的 icon

apple_touch_icon: https://img.cyfan.top/pic/img/apple-touch-icon.png # 用于苹果设备的 icon

title_join_string: ' || '  # 浏览器标签页中的标题分隔符，效果： 文章名 - 站点名

force_https: false  # 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）

highlight: # 代码高亮
  enable: true
  theme: tomorrow-night-eighties # available: github-v2 | tomorrow | tomorrow-night | tomorrow-night-eighties，更多主题可从 https://jmblog.github.io/color-themes-for-google-code-prettify/ 获取，保存为 `*.min.css` 到 `source/lib/prettify/`，在其中 .prettyprint{ background: ***; ...} 的background 值后加上 !important，例如：.prettyprint{background:#fafbfc!important; ...}

fun_features: # 一些好玩的功能
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "|" # 游标字符
    loop: true # 是否循环播放效果
  anchorjs: # 为文章内容中的标题添加锚图标
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: left # icon放置的位置： left | right
    visible: hover # 默认悬浮显示，可选：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
    icon: "♂" # 可选：§ | # | ❡ 等，留空则为默认效果
  mouse_click:  # 鼠标点击动效
    enable: true
    style: love # 目前设置两个值：values（价值观词汇） | love（爱心）

color:  # 主体颜色配置，可以从这里寻找启发： https://www.webdesignrankings.com/resources/lolcolors/
  body_bg_color: "#F8F8F8"
  navbar_bg_color: "#F6B352"
  navbar_text_color: "#FFFFFF"
  text_color: "#3c4858"
  link_color: "#3c4858"
  link_hover_color: "#000000"
  board_color: "#FFFFFF"

custom_js:   # 指定自定义 js 文件路径，路径是相对 source 目录，如 /js/custom.js
custom_css:   # 指定自定义 css 文件路径，路径是相对 source 目录，如 /css/custom.css
custom_html: ''  # 自定义底部 HTML 内容（位于 footer 上方），也可用于外部引入 js css 这些操作，注意不要和 post.custom 配置冲突

web_analytics:  # 网页访问统计
  enable: true
  baidu: 05c96804c30d57ea6de2d0bf8d5b3e73
  google:  # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
  tencent:  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage
  woyaola:  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
  cnzz:  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show

lazyload: # 对页面中的图片进行懒加载处理，可见范围外的图片不会加载
  enable: true
  onlypost: false  # 仅在文章页使用懒加载

smooth_scroll: # 平滑滚动效果，服务器加载过慢可能会影响滚动，请慎用
  enable: false

daovoice:  # 在线客服 Daovoice 参考：http://dashboard.daovoice.io
  enable: false # 是否开启在线客服聊天
  appid: ''  # 应用ID设置

aplayer:  # 音乐播放器，注意不能与 hexo-tag-aplayer 插件共用
  enable: false
  autoplay: false  # 音频自动播放
  loop: 'all'  # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'  # 播放顺序，可选值: 'list', 'random'
  theme: '#b7daff'  # 主题色
  songs:  # 歌曲列表，必须传入下列各参数，其中 url 与 cover 在本地需存于 source 目录，更多参数见文档：https://aplayer.js.org/#/zh-Hans/?id=%E5%8F%82%E6%95%B0
    - { name: 'Play', artist: '电音教主', url: '/music/Play.mp3', cover: '' }
    - { name: 'Lily', artist: '电音教主', url: '/music/Lily.mp3', cover: '' }

#---------------------------
# 页头
# Header
#---------------------------
navbar:
  blog_title:  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  menu:  # 可自行增减，若想减去某个入口，可以将值留空，显示文本关联 languages
    归档: /archives/
    分类: /categories/
    标签: /tags/
    关于: /about/
    朋友们: /links/  
    留言板: /1949/10/01/留言板/
    随口胡说: /随口胡说/ 
    项目主页: https://cyfan.top
	
	
search: # 搜索栏
  enable: true
  path: /local-search.xml # 文件引用地址，默认是下方生成位置，也可以将生成后的 local-search.xml 上传到其它位置引用，如：https://www.example.com/local-search.xml
  generate_path: /local-search.xml # 文件生成位置，必须为相对位置
  field: post
  content: true

scroll_down_arrow:  # 向下滚动的箭头
  enable: true
  banner_height_limit: 90  # 头图高度不小于指定比例，才显示箭头
  scroll_after_turning_page: true  # 翻页后自动滚动

banner_parallax: true  # 头图滚动视差


#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  statistics:  # 统计网站 PV、UV，使用的是不蒜子，显示在页脚  *不蒜子近期连接不稳定，谨慎开启
    enable: true
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

  beian:  # The footer of China's website policy, other areas keep disable
    enable: true
    icp_text: 2020213344号 # ICP证号
    police_text: 萌ICP备
    police_code: 2020213344 # 公安备案的编号，用于URL跳转查询
    police_icon: 

scroll_top_arrow:  # 向顶部滚动的箭头
  enable: true


#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: https://img.cyfan.top/pic/img/1.jpg  # 首页 Banner 头图，以下相同
  banner_img_height: 100  # 头图高度，屏幕百分比，available: 0 - 100
  post_default_img: '' # 默认的文章封面图，当没有指定 index_img 时会使用该图片，若都为空则不显示任何图片
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text: 一个在互联网角落挣扎的小小博客，很小很小。
  auto_excerpt:
    enable: true
  post_url_target: _blank  # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: true
    tag: true

# 通过 hexo new page 命令创建的页面
# Custom Page
page:
  banner_img: https://img.cyfan.top/pic/img/2.jpg
  banner_img_height: 100  # available: 0 - 100
  comments:  # 评论
    enable: true  # 开启评论
    type: gitalk 
#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: https://img.cyfan.top/pic/img/3.jpg
  banner_img_height: 100  # available: 0 - 100
  meta:  # 文章标题下方的信息
    date:  # 文章日期
      enable: true
      format: "dddd, MMMM Do YYYY, h:mm a"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数，统计基于不蒜子  *不蒜子近期连接不稳定，谨慎开启
      enable: true
      format: "{} 次"
  updated:
    enable: true
    content: 本文最后更新于：
  toc:  # 文章右侧目录
    enable: true
    headingSelector: h1,h2,h3,h4,h5,h6
  copyright:  # 版权声明
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" rel="nofollow noopener">CC BY-SA 3.0协议</a> 。转载请注明出处！'
  prev_next:  # 文章底部上一篇下一篇功能
    enable: true
  custom:  # 文章底部自定义内容
    enable: true
    content: '<img src="https://img.cyfan.top/pic/AP.jpg" class="rounded mx-auto d-block mt-5" height=40%>' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容
  comments:  # 评论
    enable: true  # 开启评论
    type: valine  # 指定使用的评论模块  available: disqus | valine | gitalk | utterances | changyan | livere  推荐 utterances
  image_zoom:  # 文章图片可点击放大
    enable: true
  math:  # 数学公式，开启之前需要更换 Markdown 渲染器，否则复杂公式会有兼容问题，具体请见 https://hexo.fluid-dev.com/docs/guide/#数学公式
    enable: false
    specific: false  # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    engine: mathjax  # 公式引擎  available: mathjax | katex

#---------------------------
# 评论
# Comments
#---------------------------

# 开启评论在上方的 post.comments 配置

# utterances
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances:
  repo:
  issue_term:
  label: utterances
  theme: github-light
  crossorigin: anonymous

# Disqus
# 国内用户不要用，已被墙
disqus:
  shortname: # your shortname

# Gitalk
# You can get yout ClientID and ClientSecret from https://github.com/settings/applications/new
# More info available at https://github.com/gitalk/gitalk#options
gitalk:
  clientID: 322bd52acff114640e23
  clientSecret: a38f4f79c3063806ea7d903de194d1cce486f786
  repo: blog
  owner: ChenYFan
  admin: ChenYFan
  id: location.pathname         
  language: zh-CN     
  labels: "['Gitalk']"  
  perPage: 30               
  pagerDirection: last         
  distractionFreeMode: false    
  createIssueManually: false     # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true.

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  app_id:  jbxznmsljbxznmsljbxznmsljbxznmsljbxznmsl
  app_key:  jbxznmsljbxznmsljbxznmsljbxznmsl
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false
  placeholder: 开车不规范，亲人两行泪。（慎言，每一条评论都需要进行博主审核，通过后自动显示，请不要重复发评论。）
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size

# Changyan
# You can get your appid from http://changyan.kuaizhan.com/setting/common/isv-mgr
# Install: http://changyan.kuaizhan.com/static/help/f-fitself.html
changyan:
  appid: ''            # your changyan application appid        # 畅言ID
  conf: ''             # conf                                   # 畅言设置
  notify: false        # beian warning message                  # 备案提示
  libopen: true        # open laboratory                        # 畅言实验室功能开关
  cyEmoji: true        # comments emoji                         # 评论表情
  cyWallsplugin: true  # Hot text matching                      # 热文配图
  cyReping: true       # hot comments                           # 热门评论
  cyReward: true       # reward                                 # 打赏
  cyQing: true         # Light comment                          # 轻评论
  cyHotusers: true     # User evaluation                        # 热评用户
  cyHotnews: true      # Hot news                               # 热门新闻
  cyHotnewswall: true  # News wall                              # 新闻墙
  cyPk: ''             # Topic debate                           # 辩论
  cyPoll: true         # vote                                   # 投票
  cyBarrage: true      # Picture barrage                        # 图片弹幕
  cyTvbarrage: true    # Video barrage                          # 视频弹幕

# Livere 来必力
# You can get your uid from https://www.livere.com/my_Livere
livere:
  uid: ''            # your livere application uid        # 来必力ID


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: https://img.cyfan.top/pic/img/4.jpg
  banner_img_height: 100  # available: 0 - 100
  subtitle: 归档 - 所有的所有都在这儿了

#---------------------------
# 分类归档页
# Categories Page
#---------------------------
category:
  banner_img: https://img.cyfan.top/pic/img/5.jpg
  banner_img_height: 100  # available: 0 - 100
  subtitle: 分类 - 是不是比较杂?

#---------------------------
# 标签归档页
# Tags Page
#---------------------------
tag:
  banner_img: https://img.cyfan.top/pic/img/6.jpg
  banner_img_height: 100  # available: 0 - 100
  subtitle: 标签 - 找找你想要的
  tagcloud: # 标签云
    min_font: 15
    max_font: 30
    unit: px  # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
#---------------------------
about:  # 以下仅为页面顶部的基本信息，更多内容请在 ./pages/about.md 中编辑，支持 markdown 和 HTML
  banner_img: https://img.cyfan.top/pic/img/7.jpg
  banner_img_height: 100  # available: 0 - 100
  subtitle:  好像是关于什么呢
  avatar: https://img.cyfan.top/pic/img/avatar.png # 头像
  name: CYF
  introduce: 一个在互联网角落挣扎的小站点  /  CYF  /  Live In China
  icons: # 更多图标可从 https://fontawesome.com/v5.10.0/icons?d=gallery 查找，并以 "图标名: url" 的格式添加在下方
    "fab fa-github": https://github.com/ChenYFan
    "fa fa-envelope": mailto:chenyf@cyfan.top
    "fab fa-twitter": https://twitter.com/ChenYF_OHHH
    "fa fa-qrcode": https://img.cyfan.top/pic/AP.jpg


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: https://img.cyfan.top/pic/img/8.jpg
  banner_img_height: 100  # available: 0 - 100
  subtitle: '咻~~页面飞走啦！！！！！'  # 打字机内容


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  banner_img: https://img.cyfan.top/pic/img/9.jpg
  banner_img_height: 100  # available: 0 - 100
  subtitle:  # 打字机内容
  items:  # 键是友链标题、值的列表内容分别是 [链接, 简介, 头像]，头像可以省略
    潘高博客: [https://blog.pangao.vip, (翻译：我只是个搞 IT的！哭笑脸), https://blog.pangao.vip/images/avatar.jpg]
    CWorld‘s Blog: [https://blog.cworld.top/, Stay hungry，Stay foolish，求知若愚，虚怀若谷。, https://www.gravatar.com/avatar/85b870f6b1a177981d3e9566e3ad7264?s=160]
    Kindyear’s Blog: [https://www.kindyear.cn/, 杂乱无章的技术小站, https://www.kindyear.cn/logo.jpg]
    小丁的博客: [https://www.xding.top/, 一个神秘的大宝贝, https://www.xding.top/face.png]
    Mystery博客: [https://blog.say521.cn/, 心有猛虎，细嗅蔷薇, https://i.loli.net/2020/03/24/1UGyfThoPz4vlgA.jpg]
    一座堤的博客: [https://www.yizuodi.cn/, 没啥寓意yizuodi即一座堤, https://www.yizuodi.cn/img/myface.jpg]
    簞純资源管理器 : [https://blog.qwqdanchun.cn, 一行代码一壶酒，何不仗键走天涯, https://i.loli.net/2020/03/27/cWqdhICkJ6yjSXs.png]	
    Jimmy‘s Blog : [https://blog.jimmyho.net/, Hi，这里是可耐的Jimmy(<ゝω·)~☆, https://blog.jimmyho.net/custom/avatar.jpg]
    godxiaolong: [https://muyiio.com, 智障程序猿, https://muyiio-1300292673.cos.ap-chongqing.myqcloud.com/博客/其它/favicon.png]
    WINKILLER: [https://www.winkiller.cf, 驱动爱好者集结地, https://i.loli.net/2020/04/04/rI9mLp6B8xnfi4X.jpg]
    TigerRoot: [https://blog.tigerroot.cn, 那有什么岁月静好，只是有人在替我们负重前行。, https://s2.ax1x.com/2020/03/08/3zdGes.png]
    伊舍导航: [https://eesdh.com, 一个在互联网角落挣扎的小小导航，很小很小。, https://gitee.com/eesdh/eesdh/raw/master/img/tx.png]
    Sukka's Blog: [https://blog.skk.moe, 童话只美在真实却从不续写, https://cdn.jsdelivr.net/npm/skx@0.2.3/avatar/192x192.png]
    Colsrch: [https://colsrch.top, 愿多年以后，我可以酌一杯清酒，烂醉如泥，梦中回到我们的曾经。, https://cdn.jsdelivr.net/gh/Colsrch/images/Colsrch/avatar.jpg]
    姑苏的猫: [https://www.islery.com, 一个有趣的地方 , https://www.islery.com/favicon.ico]
    Flexiston: [https://flexiston.com, 立即行动吧，未来要自己争取, https://cdn.jsdelivr.net/gh/Flexiston/CDN/img/avatar.png]
    Tajoy's blog: [https://tajoy.net/, 一个不会摄影的程序猿，不是一个好的艺术家。, https://wx2.sbimg.cn/2020/07/23/DiyUU.jpg]
    友链还有空位！: [https://blog.cyfan.top/1949/10/01/留言板/, 点我跑去留言！, https://img.cyfan.top/pic/？.jpg]
